_target_: nemo.collections.tts.models.voicebox.VoiceboxModel


defaults:
  - duration_predictor: default
  - audio_enc_dec@duration_predictor.audio_enc_dec: mel_voco

  - voicebox: default
  - audio_enc_dec@voicebox.audio_enc_dec: encodec_voco

optim:
  name: adamw

  lr: 1e-4
  weight_decay: 1e-2
  betas: [0.9, 0.99]
  eps: 1e-8

  # sched:
  #   name: CosineAnnealing
  #   min_lr: 5e-5
  #   warmup_ratio: 0.35

# optim_param_groups:
#   duration_predictor:
#     lr: 1e-3


tokenizer:
  _target_: naturalspeech2_pytorch.utils.tokenizer.Tokenizer
  phonemizer:
    _target_: naturalspeech2_pytorch.utils.phonemizers.espeak_wrapper.ESpeak
    language: en-us
    keep_puncs: False



cfm_wrapper:
  _target_: nemo.collections.tts.modules.voicebox_modules.ConditionalFlowMatcherWrapper

  # override in VoiceboxModel.__init__
  voicebox: null
  duration_predictor: null

  sigma: 0.
  ode_atol: 1e-5
  ode_rtol: 1e-5
  ode_step_size: 0.0625
  use_torchode: False
  torchdiffeq_ode_method: 'midpoint'   # use midpoint for torchdiffeq, as in paper
  torchode_method_klass: 'torchode.Tsit5'      # use tsit5 for torchode, as torchode does not have midpoint (recommended by Bryan @b-chiang)
  cond_drop_prob: 0.
