_target_: nemo.collections.tts.models.voicebox.VoiceboxModel


defaults:
  - tokenizer@mfa_tokenizer: mfa
  - default
  - override duration_predictor: mfa
  - override audio_enc_dec@duration_predictor.audio_enc_dec: mel_voco
  - override audio_enc_dec@voicebox.audio_enc_dec: mel_voco
  - override tokenizer: null
