_target_: nemo.collections.tts.models.voicebox.VoiceboxModel


defaults:
  - default
  # - duration_predictor: default
  - duration_predictor: nemo
  - audio_enc_dec@duration_predictor.audio_enc_dec: encodec_voco



nemo_aligner:
  _target_: nemo.collections.tts.models.aligner.AlignerModel
  # from_pretrained: "tts_en_radtts_aligner"
  from_pretrained: "tts_en_radtts_aligner_ipa"

