_target_: nemo.collections.tts.modules.voicebox_modules.NeMoDurationPredictor

defaults:
  - default

aligner: null   # handled in VoiceboxModel.__init__
audio_enc_dec: null
dim_phoneme_emb: null
aligner_kwargs: null